services:
  # PHP Service
  php:
    build: ../laravel-docker-setup/php
    restart: always
    container_name: laravel-php
    volumes:
      - ./src:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    working_dir: /var/www
    networks:
      - laravel
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: remote_host=host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Nginx Service
  nginx:
    image: nginx:alpine
    restart: always
    container_name: laravel-nginx
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - laravel

  # MySQL Service
  mysql:
    image: mysql:5.7
    container_name: laravel-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_main
      MYSQL_USER: mixalis
      MYSQL_PASSWORD: theodoropo
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  mysql-data: